---
- name: Installing MetricBeat
  hosts: webservers
  become: yes
  tasks:

  - name: Downloading The Metricbeat DEB
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Extracting & Installing Metricbeat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Dropping metricbeat.yml Config
    copy:
      src: ./metricbeat.yml
      dest: /etc/metricbeat

  - name: Enable Metricbeat Module Docker
    command: sudo metricbeat modules enable docker

  - name: Setting Up MetricBeat
    command: sudo metricbeat setup

  - name: Starting MetricBeat Service
    command: sudo service metricbeat start
